SafetyAdvisor/Controllers/EvaluationItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SafetyAdvisor.Models;
using SafetyAdvisor.Helpers;

namespace SafetyAdvisor.Controllers
{
    [Authorize(Roles = "Administrators,Editors")]
    public class EvaluationItemsController : Controller
    {
        private ApplicationDbContext db;

        public EvaluationItemsController()
            : this(new ApplicationDbContext())
        {
        }

        public EvaluationItemsController(ApplicationDbContext dbContext)
        {
            this.db = dbContext;
        }

        // GET: /EvaluationItem/
        public ActionResult Index()
        {
            return View(db.EvaluationItems.Where(ei => ei.Parent == null).ToList());
        }

        // GET: /EvaluationItem/Create
        public ActionResult Create(int? parentId)
        {
            if (parentId != null)
            {
                var _parent = db.EvaluationItems.Find(parentId);
                var _model = new EvaluationItem() { ParentId = parentId, Parent = _parent };
                return View(_model).Alert(AlertType.Info, string.Format("Creating item as child of {0} [id={1}]", _parent.Caption, _parent.Id));
            }

            return View();
        }

        // POST: /EvaluationItem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Caption,Content,IsReactive,ParentId")] EvaluationItem evaluationitem)
        {
            if (ModelState.IsValid)
            {
                db.EvaluationItems.Add(evaluationitem);
                db.SaveChanges();
                if (evaluationitem.ParentId.HasValue)
                {
                    return RedirectToAction("edit", new { id = evaluationitem.ParentId }).Alert(AlertType.Success, "Evaluation item has been created.");
                }
                else
                {
                    return RedirectToAction("index").Alert(AlertType.Success, "Evaluation item has been created.");
                }
            }

            return View(evaluationitem);
        }

        // GET: /EvaluationItem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvaluationItem evaluationitem = db.EvaluationItems.Include(ei => ei.Parent.Parent.Parent).FirstOrDefault(ei => ei.Id == id);
            if (evaluationitem == null)
            {
                return HttpNotFound();
            }
            return View(evaluationitem);
        }

        // POST: /EvaluationItem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Caption,Content,IsReactive,ParentId")] EvaluationItem evaluationitem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evaluationitem).State = EntityState.Modified;
                db.SaveChanges();
                if (evaluationitem.ParentId.HasValue)
                {
                    return RedirectToAction("edit", new { evaluationitem.ParentId }).Alert(AlertType.Success, "Evaluation item has been updated.");
                }
                else
                { 
                    return RedirectToAction("index").Alert(AlertType.Success, "Evaluation item has been updated.");
                }
            }
            return View(evaluationitem);
        }

        // GET: /EvaluationItem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvaluationItem evaluationitem = db.EvaluationItems.Find(id);
            if (evaluationitem == null)
            {
                return HttpNotFound();
            }
            return View(evaluationitem).Alert(AlertType.Danger, "Are you sure? This action cannot be undone! And if you proceed it will remove all child elements recursively.");
        }

        // POST: /EvaluationItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EvaluationItem evaluationitem = db.EvaluationItems.Find(id);
            db.DeleteRecursive(evaluationitem);
            db.SaveChanges();
            BackloadFileManager.DeleteAllFiles(evaluationitem.Id);
            return RedirectToAction("Index").Alert(AlertType.Success, "Evaluation item has been deleted.");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SafetyAdvisor/Views/EvaluationItems/Create.cshtml
@model SafetyAdvisor.Models.EvaluationItem
@using SafetyAdvisor.Helpers;

@{
    ViewBag.Title = "New evaluaiton item";
}

<div class="container">

    @Html.RenderAlerts()

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@ViewBag.Title</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("create", "evaluationitems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.Partial("_EditEvaluationItem")
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SafetyAdvisor/Views/EvaluationItems/Delete.cshtml
@model     SafetyAdvisor.Models.EvaluationItem
@using SafetyAdvisor.Helpers

@{
    ViewBag.Title = "Delete evaluation item";
}

<div class="container">

    @Html.RenderAlerts()

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@ViewBag.Title</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p>
                Are you sure you want to delete this item? This action cannot be undone. <strong>Please note that this will also delete all items associated with this item (children...and also their children etc.).</strong>
                This evaluation item has <span class="label label-danger">@Model.Children.Count()</span> direct descendants (children).
            </p>
            <hr />
            @using (Html.BeginForm("delete", "evaluationitems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.Caption, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Caption, new { @class = "form-control", disabled = true })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Content, 5, 1, new { @class = "form-control", disabled = true })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Delete" class="btn btn-primary" /> or @Html.LinkToReferrer("Cancel", @Html.ActionLink("Cancel", "index")) and go back.
                    </div>
                </div>
            }
        </div>
    </div>
</div>

SafetyAdvisor/Views/EvaluationItems/Details.cshtml
@model SafetyAdvisor.Models.EvaluationItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EvaluationItem</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SafetyAdvisor/Views/EvaluationItems/Edit.cshtml
@model SafetyAdvisor.Models.EvaluationItem
@using SafetyAdvisor.Helpers;

@{
    ViewBag.Title = "Edit evaluation item";
}

<div class="container">

    @Html.RenderAlerts()

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@ViewBag.Title</h1>
            @Html.Partial("_ParentBreadcrumbs", Model.GetFamillyTree().Reverse().ToList())
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("edit", "evaluationitems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.Partial("_EditEvaluationItem")
            }
            <hr />
            <h3>Child items<a href="@Url.Action("create", new { parentid = Model.Id })" class="btn btn-success pull-right">Add child item...</a></h3>
            @Html.Partial("_ListEvaluationItems", Model.Children)
            <hr />
            <h3>Files attached to this evaluation item</h3>
            @Html.Partial("_EvaluationItemFiles", Model)
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryfileupload")
}

SafetyAdvisor/Views/EvaluationItems/Index.cshtml
@model IEnumerable<SafetyAdvisor.Models.EvaluationItem>
@using SafetyAdvisor.Helpers

@{
    ViewBag.Title = "Evaluation items";
}

<div class="container">

    @Html.RenderAlerts()

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@ViewBag.Title</h1>
            <p>The list of evaluation items on the top level i.e. the orphans, items without a parent.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 text-right">
            <a href="@Url.Action("create")" class="btn btn-primary" role="button">Create new...</a>
        </div>
    </div>

    @Html.Partial("_ListEvaluationItems")

</div>

SafetyAdvisor/Views/EvaluationItems/_EditEvaluationItem.cshtml
@model SafetyAdvisor.Models.EvaluationItem

@Html.AntiForgeryToken()

<p>You can edit the evaluation item data below. Please note that <strong>both Caption and Content are required fields</strong>.</p>
<hr />

@Html.ValidationSummary()

@Html.HiddenFor(model => model.ParentId)

<div class="form-group">
    @Html.LabelFor(model => model.Caption, new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.TextBoxFor(model => model.Caption, new { @class = "form-control" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.TextAreaFor(model => model.Content, 10, 1, new { @class = "form-control" })
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-2"></label>
    <div class="col-md-10">
        <div class="checkbox">
            <label>
                @Html.CheckBoxFor(model => model.IsReactive)
                @Html.DisplayNameFor(model => model.IsReactive)
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-primary" /> or @Html.ActionLink("Cancel", "Index") and go back to the list.
    </div>
</div>

SafetyAdvisor/Views/EvaluationItems/_EvaluationItemFiles.cshtml
@model SafetyAdvisor.Models.EvaluationItem

<form method="post" enctype="multipart/form-data" action="/backload/uploadhandler" role="form" class="form-horizontal">
    @Html.Hidden("objectContext", @Model.Id)
    <div class="row">
        <div class="col-lg-12">
            <div id="dropzone" class="well">
                <div class="form-group">
                    <label class="control-label col-md-2"><i class="fa fa-plus-circle"></i>&nbsp;Add files</label>
                    <div class="col-md-10">
                        <input style="display:inline;" type="file" id="fileupload" name="fileupload" multiple="multiple" /> ...or just drag and drop them over here
                    </div>
                </div>
                <div class="progress hide">
                    <div class="progress-bar" role="progressbar" id="overallbar" style="width: 0%"></div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>File name</th>
                    <th class="text-center">File size (bytes)</th>
                    <th class="text-center">Options</th>
                </tr>
            </thead>
            <tbody id="filerows"></tbody>
        </table>
        <script id="template-download" type="text/x-tmpl">
            {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr>
                <td>
                    <a href="{%=file.url.replace(file.name, encodeURIComponent(file.name))%}" title="{%=file.name%}" download="{%=file.name%}"><i class="fa fa-file-text"></i>&nbsp;&nbsp;{%=file.name%}</a>
                    {% if (file.error) { %}
                    <div><span class="label label-important">Error</span> {%=file.error%}</div>
                    {% } %}
                </td>
                <td class="text-center">
                    {%=file.size%}
                </td>
                <td class="text-center">
                    <a class="delete-file" title="Delete" href="#deletefile" data-url="{%=file.delete_url%}"><i class="fa fa-trash-o"></i></a>
                </td>
            </tr>
            {% } %}
        </script>
    </div>
</div>

SafetyAdvisor/Views/EvaluationItems/_ListEvaluationItems.cshtml
@using SafetyAdvisor.Helpers
@model IEnumerable<SafetyAdvisor.Models.EvaluationItem>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Caption)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Content)
                    </th>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.IsReactive)
                    </th>
                    <th class="text-center">
                        @Html.DisplayNameFor(model => model.Children)
                    </th>
                    <th class="text-center">
                        Files
                    </th>
                    <th class="text-center">Options</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a title="Edit" href="@Url.Action("edit", "EvaluationItems", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Id)</a>
                    </td>
                    <td>
                        <a title="Edit" href="@Url.Action("edit", "EvaluationItems", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Caption)</a>
                    </td>
                    <td>
                        @string.Join("", item.Content.Take(75)) ...
                    </td>
                    <td class="text-center">
                        @if (item.IsReactive)
                        {
                            <span class="glyphicon glyphicon-ok"></span>
                        }
                    </td>
                    <td class="text-center">
                        <span class="badge">@item.Children.Count()</span>
                    </td>
                    <td class="text-center">
                        <span class="badge alert-info">@BackloadFileManager.GetFiles(item.Id).Count()</span>
                    </td>
                    <td class="text-center">
                        <a title="Edit" href="@Url.Action("edit", "EvaluationItems", new { id = item.Id })"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;&nbsp;
                        <a title="Delete" href="@Url.Action("delete", "EvaluationItems", new { id = item.Id })"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

SafetyAdvisor/Views/EvaluationItems/_ParentBreadcrumbs.cshtml
@model IEnumerable<SafetyAdvisor.Models.EvaluationItem>
@{
    var _last = Model.Last();
}

@if (Model.Count() > 1)
{
    <ol class="breadcrumb">
        @foreach (var item in Model)
        {
            if (item.Id != _last.Id)
            {
                <li>@Html.ActionLink(string.Format("{0}...", string.Join("", item.Caption.Take(20))), "edit", "evaluationitems", new { id = item.Id }, null)</li>
        }
            else
            {
                <li class="active">@item.Caption</li>
            }
        }
    </ol>
}